extends: 'eslint:recommended'
env:
  browser: true
  es6: true
ecmaFeatures:
  blockBindings: true
parserOptions:
  sourceType: module
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true
    spread: true
    experimentalObjectRestSpread: true
rules:
  indent:
    - error
    - 2
    - {"SwitchCase": 1, "VariableDeclarator": {"var": 2, "let": 2, "const": 3}}
  linebreak-style:
    - error
    - unix
  no-var: 2
  no-unused-vars: 0
  quotes:
    - error
    - single
  semi:
    - error
    - always
