env:
  browser: true
  es6: true
extends: 'eslint:recommended'
ecmaFeatures:
  blockBindings: true
parserOptions:
  sourceType: module
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true
rules:
  indent:
    - error
    - 2
    - VariableDeclarator: {"var": 2, "let": 2, "const": 3}
  linebreak-style:
    - error
    - unix
  no-var: 2
  no-unused-vars: 0
  quotes:
    - error
    - single
  semi:
    - error
    - always
